/*
 * HAT_BLE_Protocol.h
 *
 *  Created on: 2022. 5. 13.
 *      Author: Yu Jin Park
 */

#ifndef APP_HAT_BLE_PROTOCOL_H_
#define APP_HAT_BLE_PROTOCOL_H_

#include "LAP_api.h"
#include "sw_config.h"

#define HAT_PACKET_INDEX_PACKET_TYPE                    PAAR_PACKET_INDEX_PACKET_TYPE
#define HAT_PACKET_INDEX_PACKET_SERVICE_ID              PAAR_PACKET_INDEX_SERVICE_ID
#define HAT_PACKET_INDEX_SEQUENCE_NUM                   PAAR_PACKET_INDEX_SEQUENCE_NUM
#define HAT_PACKET_INDEX_DATA_LEN                       PAAR_PACKET_INDEX_DATA_LEN
#define HAT_PACKET_INDEX_DATA_CMD                       PAAR_PACKET_INDEX_BODY_DATA_CMD

#define HAT_PACKET_INDEX_ACTIVITY_RESULT_ADL_DEVICE_ID0 PAAR_PACKET_INDEX_BODY_DATA_BODY
#define HAT_PACKET_INDEX_ACTIVITY_RESULT_ADL_DEVICE_ID1 PAAR_PACKET_INDEX_BODY_DATA_BODY+1

#define HAT_PACKET_INDEX_ACITIVITY_RESULT_ACTION        PAAR_PACKET_INDEX_BODY_DATA_BODY+2
#define HAT_PACKET_INDEX_ACITIVITY_LOCATION_LEN         PAAR_PACKET_INDEX_BODY_DATA_BODY+3
#define HAT_PACKET_INDEX_ACITIVITY_LOCATION_DATA        PAAR_PACKET_INDEX_BODY_DATA_BODY+4

#define HAT_PACKET_RESULT_LOCATION_DATA                 SAAL_LOCATION

#define HAT_PACKET_RESULT_HEADER_LEN                    4
#define HAT_PACKET_RESULT_DATA_LEN                      4  

#define HAT_PACKET_RESULT_HEADER_DATA_LEN               HAT_PACKET_RESULT_HEADER_LEN+HAT_PACKET_RESULT_DATA_LEN

#define HAT_PACKET_RESULT_DATA_CMD                      0x03

#define HAT_PACKET_RESULT_LOCATION_LEN_SIZE             1

#define HAT_PACKET_RESULT_PACKET_TYPE                   PAAR_PACKET_TYPE_M2M
#define HAT_PACKET_RESULT_SERVICE_ID                    SAAL_SERVICE_ID_AAT
#define HAT_PACKET_RESULT_SEQUENCE_NUM                  0x11

void send_HAT_result_packet(uint8_t action_result);

#endif /* APP_HAT_BLE_PROTOCOL_H_ */