/*
 * ADL_info.h
 *
 *  Created on: 2022. 2. 22.
 *      Author: YuJin Park
 *
 */

#ifndef APPLICATION_CONFIG_ADL_INFO_H_
#define APPLICATION_CONFIG_ADL_INFO_H_

#define ADL_DEVICE_TYPE_WINDOW				0x01
#define ADL_DEVICE_TYPE_DRAWER				0x02
#define ADL_DEVICE_TYPE_DOOR				0x03
#define ADL_DEVICE_TYPE_COOKING_UTENSIL		0x04
#define ADL_DEVICE_TYPE_REMOTE_CONTROL		0x05
#define ADL_DEVICE_TYPE_CLEANING_SUPPLY		0x06
#define ADL_DEVICE_TYPE_REFRIGERATOR		0x07
#define ADL_DEVICE_TYPE_TV					0x08
#define ADL_DEVICE_TYPE_COFFEE_PORT			0x09
#define ADL_DEVICE_TYPE_ELECTRIC_FAN		0x0A
#define ADL_DEVICE_TYPE_HAIR_DRYER			0x0B
#define ADL_DEVICE_TYPE_VACCUM_CLEANER		0x0C
#define ADL_DEVICE_TYPE_TASMOTOR			0x0D
#define ADL_DEVICE_TYPE_MICROWAVE			0x0E
#define ADL_DEVICE_TYPE_PC					0x0F
#define ADL_DEVICE_TYPE_TOASTER				0x10
#define ADL_DEVICE_TYPE_ELECTRIC_HEATER		0x11
#define ADL_DEVICE_TYPE_FAUCET				0x12
#define ADL_DEVICE_TYPE_TOILET				0x13

#endif /* APPLICATION_CONFIG_ADL_INFO_H_ */