/*
 * AAT_main.h
 *
 *  Created on: 2021. 9. 15.
 *      Author: YuJin Park
 */

#ifndef APP_AAT_MAIN_H_
#define APP_AAT_MAIN_H_

#define MAIN_MAX_MSGQ_SIZE		10
#define MAIN_MAX_MSGQ_COUNT		10

#include <stdbool.h>
#include <stdint.h>

#define ATT_DEFAULT_ACC_ON_CHECK_MIN	3000
#define ATT_DEFAULT_ACC_ON_CHECK_MAX	10000

#define ATT_DEFAULT_ACC_OFF_CHECK_MIN	-3000
#define ATT_DEFAULT_ACC_OFF_CHECK_MAX	1500

#define ATT_DEFAULT_GYRO_ON_CHECK_MIN	100
#define ATT_DEFAULT_GYRO_ON_CHECK_MAX	10000

#define ATT_DEFAULT_GYRO_OFF_CHECK_MIN	-10000
#define ATT_DEFAULT_GYRO_OFF_CHECK_MAX	-50

#define DEFAULT_ACC_DATA_WINDOW_SIZE	20
#define DEFAULT_ACC_DATA_VALUE			0
#define DEFAULT_ACC_DATA_PERIOD_MS		100

#define DEFAULT_GYRO_DATA_WINDOW_SIZE	20

#define NUM_ACC_GYRO_AXIS				3

#define DEFAULT_ACC_GUARD_FILTER_DELAY_MS		500

#define UPDATE_VAL_SLEEP_COUNT	 100

#define PAAR_SETUP_PACKET_LEN_SENSOR_STREAM	PAAR_PACKET_HEADER_LEN+13

#define PAAR_SETUP_INDEX_SENSOR_STREAM_ACC_X  PAAR_PACKET_INDEX_BODY_DATA_BODY
#define PAAR_SETUP_INDEX_SENSOR_STREAM_ACC_Y  PAAR_PACKET_INDEX_BODY_DATA_BODY+2
#define PAAR_SETUP_INDEX_SENSOR_STREAM_ACC_Z  PAAR_PACKET_INDEX_BODY_DATA_BODY+4
#define PAAR_SETUP_INDEX_SENSOR_STREAM_GYRO_X  PAAR_PACKET_INDEX_BODY_DATA_BODY+6
#define PAAR_SETUP_INDEX_SENSOR_STREAM_GYRO_Y  PAAR_PACKET_INDEX_BODY_DATA_BODY+8
#define PAAR_SETUP_INDEX_SENSOR_STREAM_GYRO_Z  PAAR_PACKET_INDEX_BODY_DATA_BODY+10

#define PAAR_SETUP_PACKET_LEN_GYRO_STREAM	PAAR_PACKET_HEADER_LEN+5

#define TEST_STEAMING_PERIOD 		200
#define ATT_SLEEP_CNT_ACC_MODE		10
#define ATT_SLEEP_CNT_GYRO_MODE		10
#define ATT_SLEEP_CNT_SETUP_MODE	100

typedef struct
{
	uint8_t event;
	uint8_t status;
	uint8_t* msg;
}AATMainEvt_t;

enum{
	AAT_ACC_EVT = 0,
	AAT_ALS_EVT,
};

enum{
	ANALOG_ADL_ON = 0x01,
	ANALOG_ADL_OFF = 0x02,
};

enum{
	LIGHT_OFF = 0x00,
	LIGHT_ON,
};

uint8_t AAT_Main_event_send(uint8_t Main_evt, uint16_t Main_evt_state, uint8_t* msg);
void AAT_main_task_init(void);

#endif /* APP_AAT_MAIN_H_ */