/*
 * THY_environment_sensor.h
 *
 *  Created on: 2022. 05. 24.
 *      Author: Yu Jin Park
 */

#ifndef APPLICATION_THY_EVIRONMENT_SENSOR_H_
#define APPLICATION_THY_EVIRONMENT_SENSOR_H_

#include <ubinos.h>

#include <stdio.h>
#include <stdint.h>

#include "sw_config.h"
#include "hw_config.h"

#define THY_ENV_TASK_START_DELAY    5000

#define THY_ENV_REPORT_SIZE_LOCATION_LEN		1
#define THY_ENV_REPORT_PACKET_SIZE_DATA_BODY	25

enum{
    THY_ENV_EVENT_REPORT = 0,
};

#define THY_ENV_REPORT_INDEX_ENV_DATA_PRESS_0            PAAR_PACKET_INDEX_BODY_DATA_BODY
#define THY_ENV_REPORT_INDEX_ENV_DATA_PRESS_1            PAAR_PACKET_INDEX_BODY_DATA_BODY+1
#define THY_ENV_REPORT_INDEX_ENV_DATA_PRESS_DECIMAL_0    PAAR_PACKET_INDEX_BODY_DATA_BODY+2
#define THY_ENV_REPORT_INDEX_ENV_DATA_PRESS_DECIMAL_1    PAAR_PACKET_INDEX_BODY_DATA_BODY+3
#define THY_ENV_REPORT_INDEX_ENV_DATA_TEMP_0             PAAR_PACKET_INDEX_BODY_DATA_BODY+4
#define THY_ENV_REPORT_INDEX_ENV_DATA_TEMP_1             PAAR_PACKET_INDEX_BODY_DATA_BODY+5
#define THY_ENV_REPORT_INDEX_ENV_DATA_TEMP_DECIMAL_0     PAAR_PACKET_INDEX_BODY_DATA_BODY+6
#define THY_ENV_REPORT_INDEX_ENV_DATA_TEMP_DECIMAL_1     PAAR_PACKET_INDEX_BODY_DATA_BODY+7
#define THY_ENV_REPORT_INDEX_ENV_DATA_HUMIDITY_0         PAAR_PACKET_INDEX_BODY_DATA_BODY+8
#define THY_ENV_REPORT_INDEX_ENV_DATA_HUMIDITY_1         PAAR_PACKET_INDEX_BODY_DATA_BODY+9
#define THY_ENV_REPORT_INDEX_ENV_DATA_GAS_ADC_0          PAAR_PACKET_INDEX_BODY_DATA_BODY+10
#define THY_ENV_REPORT_INDEX_ENV_DATA_GAS_ADC_1          PAAR_PACKET_INDEX_BODY_DATA_BODY+11
#define THY_ENV_REPORT_INDEX_ENV_DATA_GAS_EC02_0         PAAR_PACKET_INDEX_BODY_DATA_BODY+12
#define THY_ENV_REPORT_INDEX_ENV_DATA_GAS_EC02_1         PAAR_PACKET_INDEX_BODY_DATA_BODY+13
#define THY_ENV_REPORT_INDEX_ENV_DATA_GAS_TVOC_0         PAAR_PACKET_INDEX_BODY_DATA_BODY+14
#define THY_ENV_REPORT_INDEX_ENV_DATA_GAS_TVOC_1         PAAR_PACKET_INDEX_BODY_DATA_BODY+15
#define THY_ENV_REPORT_INDEX_ENV_DATA_COLOR_RED_0        PAAR_PACKET_INDEX_BODY_DATA_BODY+16
#define THY_ENV_REPORT_INDEX_ENV_DATA_COLOR_RED_1        PAAR_PACKET_INDEX_BODY_DATA_BODY+17
#define THY_ENV_REPORT_INDEX_ENV_DATA_COLOR_GREEN_0      PAAR_PACKET_INDEX_BODY_DATA_BODY+18
#define THY_ENV_REPORT_INDEX_ENV_DATA_COLOR_GREEN_1      PAAR_PACKET_INDEX_BODY_DATA_BODY+19
#define THY_ENV_REPORT_INDEX_ENV_DATA_COLOR_BLUE_0       PAAR_PACKET_INDEX_BODY_DATA_BODY+20
#define THY_ENV_REPORT_INDEX_ENV_DATA_COLOR_BLUE_1       PAAR_PACKET_INDEX_BODY_DATA_BODY+21
#define THY_ENV_REPORT_INDEX_ENV_DATA_COLOR_CLEAR_0      PAAR_PACKET_INDEX_BODY_DATA_BODY+22
#define THY_ENV_REPORT_INDEX_ENV_DATA_COLOR_CLEAR_1      PAAR_PACKET_INDEX_BODY_DATA_BODY+23

typedef struct _THY_env_msgq_event_t {
	uint8_t event;
	uint8_t status;
	uint8_t * msg;
} THY_env_msgq_event_t;

int THY_env_event_send(uint8_t evt, uint8_t state, uint8_t * msg);

void THY_envrionment_report_task_init(void);

#endif /* APPLICATION_THY_EVIRONMENT_SENSOR_H_ */